feat: OPX3.1-dev1 (#22)
* Feature: Static L2 VxLAN Support
* Bugfix: Fix NAS MAC callback event
* Bugfix: Fix IP address family for MAC events
* Bugfix: Check bridgeport ID before flushing
* Update: Add IPv6 Extended route configuration handle
* Update: Add handle_profile_map() back to the code
* Update: Add split horizon attribute set for subport
* Update: Ignore MAC flush event from SAI
* Update: Add support for virtual rif attribute as part of RIF configuration
* Update: Add IPv4 and IPv6 interface statistics attributes
* Update: Add support for setting multicast lookup key in VLAN
* Update: Add support port VLAN subport flush
* Update: Clear stat implementation for bridge, bridge port, and tunnel
* Update: ACL BRIDGE_TYPE filtering
* Update: Support ACL table utilization
* Update: API to support tag/untag packet drop on LAG
* Update: Support to retrieve ACL profile information and program to SAI
          as key-value pair

Signed-off-by: Garrick He <garrick_he@dell.com>

diff --git a/src/unit_test/run_test b/src/unit_test/run_test
--- a/src/unit_test/run_test
+++ b/src/unit_test/run_test
@@ -3,7 +3,7 @@
 #Script will kill the base_nas svc and then execute ./run_test
 
 touch /etc/no-reboot
-nas_pid=`ps aux | grep '/opt/dell/os10/bin/base_nas$' | grep -v 'grep' | awk '{print $2}'`
+nas_pid=`ps aux | grep '/usr/bin/opx_nas_daemon$' | grep -v 'grep' | awk '{print $2}'`
 if [ -n "$nas_pid" ]; then
     echo "Kill base_nas daemon with PID $nas_pid"
     kill -9 $nas_pid
@@ -18,6 +18,12 @@ fi
 ./nas_ndi_init_unittest
 if [ "$?" != "0" ]; then
     echo "Test Failed for NDI-INIT UT"
+    exit 1
+fi
+
+./nas_ndi_tunnel_map_ut
+if [ "$?" != "0" ]; then
+    echo "Test Failed for NDI-TUNNEL UT"
     exit 1
 fi
 
