Adde features and bugfixes
* Feature: VxLAN Support
* Update: Add Ipv6 Extended route configuration handle
* Bugfix: Fix nas mac callback event
* Update: Add split horizon attribute set for subport
* Update: Ignore mac flush event from SAI
* Update: Add support for virtual rif attribute as part of RIF configuration
* Update: Add ipv4 and ipv6 interface statistics attributes
* Update: Add support for setting multicast lookup key in VLAN
* Update: Add support port vlan subport flush
* Update: Clear stat implementation for bridge,bridge port and tunnel
* Bugfix: Fix ip address family for mac events

Signed-off-by: Atanu Mandal <atanu_mandal@dell.com>

diff --git a/src/unit_test/run_test b/src/unit_test/run_test
--- a/src/unit_test/run_test
+++ b/src/unit_test/run_test
@@ -21,6 +21,12 @@ if [ "$?" != "0" ]; then
     exit 1
 fi
 
+./nas_ndi_tunnel_map_ut
+if [ "$?" != "0" ]; then
+    echo "Test Failed for NDI-TUNNEL UT"
+    exit 1
+fi
+
 ./nas_ndi_obj_cache_ut
 if [ "$?" != "0" ]; then
     echo "Test Failed for NDI-OBJ-CACHE UT"
@@ -41,6 +47,7 @@ if [ "$?" != "0" ]; then
     exit 1
 fi
 
+./nas_ndi_vlan_mcast_ut
 
 echo "UT execution result: Pass"
 exit 0
